# Generated by Django 3.1.5 on 2021-01-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210117_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='default_email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='default_full_name',
        ),
    ]
