# Generated by Django 3.1.5 on 2021-01-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
