# Generated by Django 3.1.5 on 2021-01-31 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210117_0808'),
        ('contact', '0002_message_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='profiles.userprofile'),
        ),
    ]
