# Generated by Django 3.1.5 on 2021-01-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_on',
            new_name='createdon',
        ),
    ]
