# Generated by Django 3.1.5 on 2021-01-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210118_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(default='', max_length=50)),
                ('comment', models.TextField()),
                ('writtenon', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['writtenon'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['createdon']},
        ),
    ]
