# Generated by Django 3.1.5 on 2021-01-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210117_0808'),
        ('blogs', '0004_auto_20210120_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='profiles.userprofile'),
        ),
    ]
