# Generated by Django 3.1.5 on 2021-01-27 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_tour_start_time'),
        ('blogs', '0008_auto_20210121_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='tours.tour'),
        ),
    ]
