# Generated by Django 3.1.5 on 2021-01-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image_url',
        ),
    ]
