# Generated by Django 3.1.5 on 2021-01-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20210122_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='rating',
        ),
    ]
