# Generated by Django 3.1.5 on 2021-01-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_tour_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
