# Generated by Django 3.1.5 on 2021-01-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20210122_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
