# Generated by Django 3.1.5 on 2021-01-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='review_emoji',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.rating'),
        ),
    ]
