# Generated by Django 3.1.5 on 2021-01-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_auto_20210122_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
