# Generated by Django 3.1.5 on 2021-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tour_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
