# Generated by Django 3.1.5 on 2021-01-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_auto_20210124_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='start_time',
            field=models.CharField(default='', max_length=254),
        ),
    ]
