# Generated by Django 3.1.4 on 2021-01-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='quantity',
            new_name='tour_count',
        ),
    ]
