# Generated by Django 3.1.4 on 2021-01-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210113_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tour_count',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
