# Generated by Django 3.1.4 on 2021-01-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210113_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='lineitem_disc_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
    ]
