# Generated by Django 3.1.5 on 2021-01-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='tour_date',
            field=models.CharField(default='', max_length=40),
        ),
    ]
